export const MOCK_CHECKOUT = {
  __typename: 'Checkout',
  id: 'gid://shopify/Checkout/040f1764ab86f04b57a69167a10736a2?key=a7ebde939b6a5531e7b8e644d19ca511',
  ready: true,
  requiresShipping: true,
  note: null,
  paymentDue: {
    amount: '1485.9',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  paymentDueV2: {
    amount: '1485.9',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  webUrl:
    'https://blizzardrush.myshopify.com/58975060073/checkouts/040f1764ab86f04b57a69167a10736a2?key=a7ebde939b6a5531e7b8e644d19ca511',
  orderStatusUrl: null,
  taxExempt: false,
  taxesIncluded: false,
  currencyCode: 'CAD',
  totalTax: {
    amount: '0.0',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  totalTaxV2: {
    amount: '0.0',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  lineItemsSubtotalPrice: {
    amount: '1485.9',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  subtotalPrice: {
    amount: '1485.9',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  subtotalPriceV2: {
    amount: '1485.9',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  totalPrice: {
    amount: '1485.9',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  totalPriceV2: {
    amount: '1485.9',
    currencyCode: 'CAD',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: {
        amount: 'Decimal',
        currencyCode: 'CurrencyCode',
      },
      implementsNode: false,
    },
  },
  completedAt: null,
  createdAt: '2024-07-12T23:43:46Z',
  updatedAt: '2024-07-15T02:15:48Z',
  email: null,
  discountApplications: [],
  appliedGiftCards: [],
  shippingAddress: null,
  shippingLine: null,
  customAttributes: [],
  order: null,
  lineItems: [
    {
      id: 'gid://shopify/CheckoutLineItem/415457350779930?checkout=040f1764ab86f04b57a69167a10736a2',
      title: 'The Complete Snowboard',
      variant: {
        id: 'gid://shopify/ProductVariant/41545735077993',
        title: 'Dawn',
        price: {
          amount: '699.95',
          currencyCode: 'CAD',
          type: {
            name: 'MoneyV2',
            kind: 'OBJECT',
            fieldBaseTypes: {
              amount: 'Decimal',
              currencyCode: 'CurrencyCode',
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: '699.95',
          currencyCode: 'CAD',
          type: {
            name: 'MoneyV2',
            kind: 'OBJECT',
            fieldBaseTypes: {
              amount: 'Decimal',
              currencyCode: 'CurrencyCode',
            },
            implementsNode: false,
          },
        },
        weight: 10,
        available: true,
        sku: '',
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: 'gid://shopify/ProductImage/31744903938153',
          src: 'https://cdn.shopify.com/s/files/1/0589/7506/0073/files/Main_589fc064-24a2-4236-9eaf-13b2bd35d21d.jpg?v=1716602383',
          altText:
            'Top and bottom view of a snowboard. The top view shows abstract circles and lines in shades of teal.\n          The bottom view shows abstract circles and lines in shades of purple and blue with the text “SHOPIFY” in a\n          sans serif typeface on top.',
          width: 1600,
          height: 1600,
          type: {
            name: 'Image',
            kind: 'OBJECT',
            fieldBaseTypes: {
              altText: 'String',
              height: 'Int',
              id: 'ID',
              url: 'URL',
              width: 'Int',
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: 'Color',
            value: 'Dawn',
            type: {
              name: 'SelectedOption',
              kind: 'OBJECT',
              fieldBaseTypes: {
                name: 'String',
                value: 'String',
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: 'UnitPriceMeasurement',
            kind: 'OBJECT',
            fieldBaseTypes: {
              measuredType: 'UnitPriceMeasurementMeasuredType',
              quantityUnit: 'UnitPriceMeasurementMeasuredUnit',
              quantityValue: 'Float',
              referenceUnit: 'UnitPriceMeasurementMeasuredUnit',
              referenceValue: 'Int',
            },
            implementsNode: false,
          },
        },
        product: {
          id: 'gid://shopify/Product/7313620631657',
          handle: 'the-complete-snowboard',
          type: {
            name: 'Product',
            kind: 'OBJECT',
            fieldBaseTypes: {
              availableForSale: 'Boolean',
              createdAt: 'DateTime',
              description: 'String',
              descriptionHtml: 'HTML',
              handle: 'String',
              id: 'ID',
              images: 'ImageConnection',
              onlineStoreUrl: 'URL',
              options: 'ProductOption',
              productType: 'String',
              publishedAt: 'DateTime',
              title: 'String',
              updatedAt: 'DateTime',
              variants: 'ProductVariantConnection',
              vendor: 'String',
            },
            implementsNode: true,
          },
        },
        type: {
          name: 'ProductVariant',
          kind: 'OBJECT',
          fieldBaseTypes: {
            availableForSale: 'Boolean',
            compareAtPrice: 'MoneyV2',
            id: 'ID',
            image: 'Image',
            price: 'MoneyV2',
            product: 'Product',
            selectedOptions: 'SelectedOption',
            sku: 'String',
            title: 'String',
            unitPrice: 'MoneyV2',
            unitPriceMeasurement: 'UnitPriceMeasurement',
            weight: 'Float',
          },
          implementsNode: true,
        },
      },
      quantity: 2,
      customAttributes: [],
      discountAllocations: [],
      type: {
        name: 'CheckoutLineItem',
        kind: 'OBJECT',
        fieldBaseTypes: {
          customAttributes: 'Attribute',
          discountAllocations: 'DiscountAllocation',
          id: 'ID',
          quantity: 'Int',
          title: 'String',
          variant: 'ProductVariant',
        },
        implementsNode: true,
      },
      hasNextPage: {
        value: true,
      },
      hasPreviousPage: false,
      variableValues: {
        id: 'gid://shopify/Checkout/040f1764ab86f04b57a69167a10736a2?key=a7ebde939b6a5531e7b8e644d19ca511',
      },
    },
    {
      id: 'gid://shopify/CheckoutLineItem/415457355695130?checkout=040f1764ab86f04b57a69167a10736a2',
      title: 'The Compare at Price Snowboard',
      variant: {
        id: 'gid://shopify/ProductVariant/41545735569513',
        title: 'Default Title',
        price: {
          amount: '785.95',
          currencyCode: 'CAD',
          type: {
            name: 'MoneyV2',
            kind: 'OBJECT',
            fieldBaseTypes: {
              amount: 'Decimal',
              currencyCode: 'CurrencyCode',
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: '785.95',
          currencyCode: 'CAD',
          type: {
            name: 'MoneyV2',
            kind: 'OBJECT',
            fieldBaseTypes: {
              amount: 'Decimal',
              currencyCode: 'CurrencyCode',
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: '',
        compareAtPrice: {
          amount: '885.95',
          currencyCode: 'CAD',
          type: {
            name: 'MoneyV2',
            kind: 'OBJECT',
            fieldBaseTypes: {
              amount: 'Decimal',
              currencyCode: 'CurrencyCode',
            },
            implementsNode: false,
          },
        },
        compareAtPriceV2: {
          amount: '885.95',
          currencyCode: 'CAD',
          type: {
            name: 'MoneyV2',
            kind: 'OBJECT',
            fieldBaseTypes: {
              amount: 'Decimal',
              currencyCode: 'CurrencyCode',
            },
            implementsNode: false,
          },
        },
        image: {
          id: 'gid://shopify/ProductImage/31744904167529',
          src: 'https://cdn.shopify.com/s/files/1/0589/7506/0073/files/snowboard_sky.png?v=1716602383',
          altText:
            'Top and bottom view of a snowboard. The top view shows pixelated clouds, with the top-most one being\n        the shape of the Shopify bag logo. The bottom view has a pixelated cloudy sky with blue, pink and purple\n        colours.',
          width: 3097,
          height: 3908,
          type: {
            name: 'Image',
            kind: 'OBJECT',
            fieldBaseTypes: {
              altText: 'String',
              height: 'Int',
              id: 'ID',
              url: 'URL',
              width: 'Int',
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: 'Title',
            value: 'Default Title',
            type: {
              name: 'SelectedOption',
              kind: 'OBJECT',
              fieldBaseTypes: {
                name: 'String',
                value: 'String',
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: 'UnitPriceMeasurement',
            kind: 'OBJECT',
            fieldBaseTypes: {
              measuredType: 'UnitPriceMeasurementMeasuredType',
              quantityUnit: 'UnitPriceMeasurementMeasuredUnit',
              quantityValue: 'Float',
              referenceUnit: 'UnitPriceMeasurementMeasuredUnit',
              referenceValue: 'Int',
            },
            implementsNode: false,
          },
        },
        product: {
          id: 'gid://shopify/Product/7313620828265',
          handle: 'the-compare-at-price-snowboard',
          type: {
            name: 'Product',
            kind: 'OBJECT',
            fieldBaseTypes: {
              availableForSale: 'Boolean',
              createdAt: 'DateTime',
              description: 'String',
              descriptionHtml: 'HTML',
              handle: 'String',
              id: 'ID',
              images: 'ImageConnection',
              onlineStoreUrl: 'URL',
              options: 'ProductOption',
              productType: 'String',
              publishedAt: 'DateTime',
              title: 'String',
              updatedAt: 'DateTime',
              variants: 'ProductVariantConnection',
              vendor: 'String',
            },
            implementsNode: true,
          },
        },
        type: {
          name: 'ProductVariant',
          kind: 'OBJECT',
          fieldBaseTypes: {
            availableForSale: 'Boolean',
            compareAtPrice: 'MoneyV2',
            id: 'ID',
            image: 'Image',
            price: 'MoneyV2',
            product: 'Product',
            selectedOptions: 'SelectedOption',
            sku: 'String',
            title: 'String',
            unitPrice: 'MoneyV2',
            unitPriceMeasurement: 'UnitPriceMeasurement',
            weight: 'Float',
          },
          implementsNode: true,
        },
      },
      quantity: 1,
      customAttributes: [],
      discountAllocations: [],
      type: {
        name: 'CheckoutLineItem',
        kind: 'OBJECT',
        fieldBaseTypes: {
          customAttributes: 'Attribute',
          discountAllocations: 'DiscountAllocation',
          id: 'ID',
          quantity: 'Int',
          title: 'String',
          variant: 'ProductVariant',
        },
        implementsNode: true,
      },
      hasNextPage: false,
      hasPreviousPage: {
        value: true,
      },
      variableValues: {
        id: 'gid://shopify/Checkout/040f1764ab86f04b57a69167a10736a2?key=a7ebde939b6a5531e7b8e644d19ca511',
      },
    },
  ],
  type: {
    name: 'Checkout',
    kind: 'OBJECT',
    fieldBaseTypes: {
      appliedGiftCards: 'AppliedGiftCard',
      completedAt: 'DateTime',
      createdAt: 'DateTime',
      currencyCode: 'CurrencyCode',
      customAttributes: 'Attribute',
      discountApplications: 'DiscountApplicationConnection',
      email: 'String',
      id: 'ID',
      lineItems: 'CheckoutLineItemConnection',
      lineItemsSubtotalPrice: 'MoneyV2',
      note: 'String',
      order: 'Order',
      orderStatusUrl: 'URL',
      paymentDue: 'MoneyV2',
      ready: 'Boolean',
      requiresShipping: 'Boolean',
      shippingAddress: 'MailingAddress',
      shippingLine: 'ShippingRate',
      subtotalPrice: 'MoneyV2',
      taxExempt: 'Boolean',
      taxesIncluded: 'Boolean',
      totalPrice: 'MoneyV2',
      totalTax: 'MoneyV2',
      updatedAt: 'DateTime',
      webUrl: 'URL',
    },
    implementsNode: true,
  },
}
