name: Playwright Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Fetch and Set Vercel Preview URL
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Fetching deployments for PR #$PR_NUMBER"

          DEPLOYMENTS=$(curl -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" "https://api.vercel.com/v6/deployments")
          echo "Deployments fetched: $DEPLOYMENTS"

          # Verify if the deployments contain the PR ID
          if echo "$DEPLOYMENTS" | jq -e --arg prNum "$PR_NUMBER" '.deployments[] | select(.meta.githubPrId == $prNum)' > /dev/null; then
            echo "PR ID $PR_NUMBER found in deployments"
          else
            echo "PR ID $PR_NUMBER not found in deployments"
            exit 1
          fi

          PREVIEW_URL=$(echo $DEPLOYMENTS | jq -r --arg prNum "$PR_NUMBER" '.deployments[] | select(.meta.githubPrId == $prNum) | .url' | head -n 1)
          echo "Selected URL: $PREVIEW_URL"

          if [ -z "$PREVIEW_URL" ]; then
            echo "No preview URL found for PR $PR_NUMBER"
            exit 1
          else
            # Ensure the URL starts with https://
            if [[ $PREVIEW_URL != http* ]]; then
              PREVIEW_URL="https://$PREVIEW_URL"
            fi
            echo "Formatted URL: $PREVIEW_URL"
            echo "VERCEL_PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Run Playwright tests
        run: pnpm exec playwright test --retries=1
        env:
          VERCEL_PREVIEW_URL: ${{ env.VERCEL_PREVIEW_URL }}
          STOREFRONT_API_ACCESS_TOKEN: ${{ secrets.STOREFRONT_API_ACCESS_TOKEN }}
          STOREFRONT_API_URL: ${{ secrets.STOREFRONT_API_URL }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
